### PR TITLE
Add card meta tags

### PR DESCRIPTION
**Pull request by hnrysmth**
Hi there, love the project ❤️ 

Just noticed there's no meta tags on the website though and figured this was something small but important I could maybe help a little with. I've run the code in this PR through [Twitter's card testing tool](https://cards-dev.twitter.com/validator) and here's how it came out.

screen shot 2017-12-05 at 20 02 33

It's possible to do more than this with these tags but I thought I'd try the quick fixes first! 😇

### CODE REVIEW

**Comment by hnrysmth** [comment]
Hmmm thinking about it more... maybe this looks a lot better with the shorter copy from the front page of the site...

screen shot 2017-12-05 at 20 09 12

What d'you reckon?

**Comment by devongovett** [comment]
I like the second option 👍 Thanks!

**Comment by hnrysmth** [comment]
No probs, updated the commit with those words!

**Comment by devongovett** [comment]
awesome, thanks!

**Pull request merged**
