### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by imbsky**
I cleaned up and unified because indent and code style were not unified.
Semicolons are omitted, but I really don't care about that. Should we not omit it?

### CODE REVIEW

**Comment by jthegedus** [comment]
This may be easier to land and better enforce with a more incremental approach; eg a pre-commit hook and prettier. Editorconfig requires all contributors to use an IDE plugin etc whereas pre-commit does not

**Comment by DeMoorJasper** [comment]
I'm gonna close this PR for now. Feel free to reopen this with a pre-commit hook and prettier or something similar.

This seems to have a lot of conflicts at the moment.

**Comment by imbsky** [comment]
I'm currently working on this. I will push new some commits.

**Comment by DeMoorJasper** [comment]
@imbsky Feel free to open a new PR with those changes based on the current master

**Comment by imbsky** [comment]
@DeMoorJasper 👌

**Pull request closed without merging**
