### PR TITLE
Simplified "getting started" code blocks

### PR DESCRIPTION
**Pull request by halo**
The first impression is important. 

I propose these code steps that look like 4 steps be visually reduced to 2.

I did a visual check on the build of every locale to make sure there is no broken Markdown.

---

screen shot 2018-08-29 at 17 24 15

---

### EDIT:
In the PR code it's `# npm` not `# NPM` as in the screenshot.

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
I like it, but now it isn't really copiable as they should only run one of those commands not both.

Copying those codeblocks would result in installing using both yarn and npm

**Comment by halo** [comment]
@DeMoorJasper thank you for your feedback!

>  they should only run one of those commands not both

That's why ideally it should look like the following. Default to convention but offer an alternative (that isn't really possible with default Markdown so I opted for what came closest).

screen shot 2018-08-30 at 09 56 35

Another alternative in plain Markdown would be this, but it requires translation:

```bash
npm install -g parcel-bundler

# Or if you use Yarn:
yarn global add parcel-bundler
```

---

> Copying those codeblocks would result in installing using both yarn and npm

It looks like Parcel works under the assumption that people already know what `Yarn` and `npm` are. Given that assumption, they won't run both commands but only one. 

If it's not clear to the users what the difference is, or of there is any doubt about it, there should be no mention at all of `Yarn` and Parcel should just recommend `npm` for starters.

**Comment by DeMoorJasper** [comment]
@halo this makes me lean more towards keeping it as is as I really don’t wanna see yarn go away in the docs. I’d rather see npm go away

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jthegedus** [comment]
Just my 2c on converting the docs to use a documentation tool.

While [Gatsby](https://www.gatsbyjs.org/) and things like [Docusaurus](https://docusaurus.io/) are cool, I'd like to see the site built using Parcel. The simplicity it has now is nice, except for the lack of simple things like a dev-server. Maybe using `mdx` with the [parcel-plugin](https://github.com/mdx-js/mdx/tree/master/packages/parcel-plugin-mdx) would be the way to get the best of all worlds?

- simplicity
- parcel DX
- simple JS for solving the problem this issue raised
- doggfooding

Just an idea. I'll be toying with it for another project over the next week. Will link back with thoughts/results :+1:

**Pull request closed without merging**
