### PR TITLE
H in GitHub should be capitalized

### PR DESCRIPTION
**Pull request by michaelmior**

### CODE REVIEW

**Comment by ronkorving** [comment]
I was gonna make this PR, glad I checked to see if it was already here ;)

**Comment by michaelmior** [comment]
Obviously super minor, but I appreciate these things being consistent. Glad to see I'm not the only one :)

**Comment by ronkorving** [comment]
It's also a nice way to get acquainted with the project and it's repo :) I just found out about Parcel today, and it looks amazing!

**Comment by michaelmior** [comment]
Well, this being the website repo I'm not sure how much it helps with getting acquainted with Parcel, but I'm definitely interested in checking it out :)

**Comment by ronkorving** [comment]
The people surrounding the eco system :) Nice to meet you! :)

**Pull request merged**
