### PR TITLE
Added info about running Parcel without installing it globally

### PR DESCRIPTION
**Pull request by RapidOwl**
Hi! I was trying to use Parcel with Netlify's build agent and had to do it as described in my change to the Production doc. I wondered if this information might be useful for other people.

I'm sorry I'm not able to localise the text.

### CODE REVIEW

**Comment by RapidOwl** [comment]
Thanks! I'll update it this evening.

**Comment by RapidOwl** [comment]
Is that updated script going to work? Installing Parcel as --save-dev won't create a shortcut to the parcel command.

**Comment by DeMoorJasper** [comment]
@RapidOwl npm automatically adds `node_modules/bin` into the execution path, so it knows all commands in node_modules

**Comment by RapidOwl** [comment]
@DeMoorJasper This doesn't work on Windows. Do you mind if I add a bit more for that use case?

**Comment by DeMoorJasper** [comment]
@RapidOwl Alright, forgot windows is always a special case for a minute

**Pull request merged**
