### PR TITLE
Update html.md

### PR DESCRIPTION
**Pull request by BigPackie**
Added documentation for usage of  PostHTML  **posthtml.config.js**   config file with examples ( _posthtml-modules_, _posthtml-shorten_ ) and notes about  caveats.

### CODE REVIEW

**Review by DeMoorJasper — APPROVED** [review]

**Comment by BigPackie** [comment]
Now all that remains is to wait for somebody to merge it?

**Comment by DeMoorJasper** [comment]
@BigPackie yes, but unfortunately we can't merge if Vercel deployment fails... Not sure why though as I can't see the logs.

**Comment by BigPackie** [comment]
Is there somebody you can contact to solve this?

**Comment by DeMoorJasper** [comment]
@BigPackie fixed it, your usage of sample was incorrect apparently

**Comment by BigPackie** [comment]
Thx a lot.  Can you share me a link about correct usage of those sample tags, so I don't make the same mistake next time?

**Comment by BigPackie** [comment]
One more thing, I realized the string `{{headerTitle}}` does not show up in the website within my example. That's a problem. How is it possible to make it visible?

**Comment by mischnic** [comment]
> so I don't make the same mistake next time?

I always copy them from another page.
Also: the whole point of these tags was to have the complete, self-contained example in a single "code sample" box and not distributed across multiple paragraphs.

**Pull request merged**
