### PR TITLE
Translate into Chinese Traditional (zh-tw)

### PR DESCRIPTION
**Pull request by osk2**
Hi,

I just completed Chinese (Traditional) translation of Parcel website. 💪 
And there are two things may need to review or help:

1. I can't get search input to work on my machine, seems it needs some configuration in Algolia DocSearch maybe?
2. The text in language selector of Chinese has been changed from "中文"(Chinese) to "简体中文"(Chinese Simplified) to avoid confusion.

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
For search it needs to get added to this config: https://github.com/algolia/docsearch-configs/blob/master/configs/parceljs.json

I'll open a PR as soon as this gets merged.

**Comment by osk2** [comment]
Just translated all recent commits, should be good to merge now :)

**Comment by QC-L** [comment]
@osk2 結構不對，麻煩修改下

**Comment by QC-L** [comment]
@osk2 結構不對，麻煩修改下

**Comment by QC-L** [comment]
@osk2 結構不對，麻煩修改下

**Comment by QC-L** [comment]
@osk2 結構不對，麻煩修改下

**Comment by osk2** [comment]
I'm still update the brach with recently changes, hope I can finish this by tomorrow.

**Comment by osk2** [comment]
@QC-L All changes were synced into this branch now 🎉

**Comment by QC-L** [comment]
image

@osk2

**Comment by QC-L** [comment]
@osk2 Can't merge, please check your document

**Comment by osk2** [comment]
I'm able to merge into master on my machine without any conflict. Looks like @DeMoorJasper still not approved this PR, I think that's the problem maybe?

**Comment by DeMoorJasper** [comment]
@osk2 Yeah it's because I blocked merge, I'll merge it

**Comment by osk2** [comment]
DocSearch still not working.
@DeMoorJasper can you please have a look if there's any config I missed.

**Comment by DeMoorJasper** [comment]
@osk2 it updates every 24hours so might e that. But its been a little while so maybe not. I’ll have a look in a bit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
