### PR TITLE
[ru] Rewrite main page texts

### PR DESCRIPTION
**Pull request by sashasushko**
Hi. I made few edits in russian version of main page. Because in some sentences, especially in features block, there were phrases in "Google translated" style.

For example russian "Свяжите все свои ресурсы" ("Bundle all your assets") is more like "Link all you resources". I suggest translating as "Сборка всех ваших зависимостей" ("[Parcel will] bundle all your dependencies").

---

I don't know you guys will plan to support i18n at second version or not. But if yes... Or if first version of website will be available still a long time, I can help with russian l10n on other pages.

### CODE REVIEW

**Comment by sashasushko** [comment]
@DeMoorJasper can you please add reviewers? Because I have no rights.

**Comment by DeMoorJasper** [comment]
@sashasushko I can approve it but our vercel deploy is broken anyway, so can't really deploy it

**Review by DeMoorJasper — APPROVED** [review]

**Comment by sashasushko** [comment]
Ok, i got it. Thank you @DeMoorJasper. But how about my question: you will plan to support i18n at second version or not? Even deploy doesn't work I can fix errors still.

**Comment by DeMoorJasper** [comment]
Probably but we should probably focus on finishing the english version first

**Comment by sashasushko** [comment]
😿

**Pull request closed without merging**
