### PR TITLE
Russian translation: actualize transforms.md

### PR DESCRIPTION
**Pull request by lex111**
Updating in accordance with https://github.com/parcel-bundler/website/commit/be0d48a74a1cfe7b78497e0c85c6a93bc4d87d71

### CODE REVIEW

**Comment by lex111** [comment]
Why Travis fails?

**Comment by lex111** [comment]
ping @DeMoorJasper

**Comment by DeMoorJasper** [comment]
That's a travis init bug, happens if something fails with installing node or yarn

**Comment by lex111** [comment]
Okay, this is a minor change, can you accept this PR?

**Pull request merged**
