### PR TITLE
Fix language-dropdown styles

### PR DESCRIPTION
**Pull request by cherniavskii**
Before:
peek 2017-12-17 18-50

After:
peek 2017-12-17 18-51

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Would be cool if u could completely fix it by adding in the flags it represents (as svg or images), it's supposed to be emoji flags but it only works on mobile and os x

**Comment by koddr** [comment]
@DeMoorJasper @cherniavskii 

Good idea, btw. For example, this SVG flags are very nice https://github.com/lipis/flag-icon-css

**Comment by davidnagli** [comment]
What if we use something like [emojie](https://github.com/lautis/emojie) to automatically display fallbacks for the emojis?

**Comment by cherniavskii** [comment]
Didn't actually know that's emoji :D
I'll look for a better solution then

**Comment by brandon93s** [comment]
Even with "emojie" we'll need to bring our own images. These may work: https://emojipedia.org/flags/

US: https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/flag-for-united-states_1f1fa-1f1f8.png
RU: https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/flag-for-russia_1f1f7-1f1fa.png
KR: https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/flag-for-south-korea_1f1f0-1f1f7.png
CN: https://emojipedia-us.s3.amazonaws.com/thumbs/120/apple/118/flag-for-china_1f1e8-1f1f3.png

**Comment by devongovett** [comment]
yeah I guess we should fix the emoji if they don't work cross platform. I wrote [apple-color-emoji](https://github.com/devongovett/apple-color-emoji/) for this though I'm not sure the legality of using those emoji images...

**Pull request merged**
