### PR TITLE
better mobile layout and behavior

### PR DESCRIPTION
**Pull request by DanielRuf**
* add paddings for small screens and define min-width
* enable momentum scrolling

### CODE REVIEW

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Another friendly bump.

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
Can we reopen this?

**Comment by DeMoorJasper** [comment]
Sure, I just closed it because the merge conflicts have been here for a while

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DanielRuf** [comment]
See https://github.com/parcel-bundler/website/pull/218/files

**Pull request closed without merging**
