### PR TITLE
Add node version 6+ requirement in english and portuguese

### PR DESCRIPTION
**Pull request by lrn2prgrm**
As discussed in the Slack this information need to get added. I attach my proposal in this two languages.

### CODE REVIEW

**Comment by brandon93s** [comment]
I missed the conversations in Slack, but Node 6 support is in progress: https://github.com/parcel-bundler/parcel/pull/253. I believe our intent is to continue to support Node 6.

**Comment by lrn2prgrm** [comment]
Should I edit to say 6+ then? That information is still missing

**Comment by lrn2prgrm** [comment]
@brandon93s now says node 6+. I think it is still important to say it on getting started.

**Comment by DeMoorJasper** [comment]
@lrn2prgrm I don't really think anyone uses a version below Node 6 and it will pop an error on installation anyway?

**Comment by brandon93s** [comment]
There is still plenty of usage on Node < 6 ([stats](https://nodejs.org/metrics/)), but since npm & yarn will prompt on failure we'll close this out.

**Pull request closed without merging**
