### PR TITLE
Add RU lang translations

### PR DESCRIPTION
**Pull request by koddr**
* [site] Translate index and layout pages
* [docs] Translate Getting Started

Working in active process to translate Parcel's docs.

### CODE REVIEW

**Comment by devongovett** [comment]
Awesome, keep it coming! 👏

**Comment by koddr** [comment]
@devongovett @davidnagli 

Ok, I finish translation. Make review please.

**Comment by devongovett** [comment]
Amazing thank you!! Now available on https://ru.parceljs.org/

**Comment by davidnagli** [comment]
@koddr Can we work on improving these translations together?

**Comment by koddr** [comment]
@devongovett thank you, Devon! I ❤️ Parcel!

@davidnagli Yes, of course! Can I add you to my own Parcel's translators team on GitHub organization?

**Comment by davidnagli** [comment]
@koddr Ya, sure!

**Comment by koddr** [comment]
@davidnagli added to here https://github.com/orgs/webartisans-org/teams/translators

**Pull request merged**
