### PR TITLE
zh-cn docs: fix index.html error

### PR DESCRIPTION
**Pull request by QC-L**

### CODE REVIEW

**Comment by brandon93s** [comment]
@QC-L - Mind providing some insights into the differences between the two?

Thanks

**Comment by QC-L** [comment]
@brandon93s Word order problems, Chinese users will make ambiguity. 
I'm the maintainer of Chinese documents.

**Comment by QC-L** [comment]
@brandon93s Hi, Can you give me permission to make it easier for me to manage Chinese documents?

**Comment by devongovett** [comment]
@QC-L I've invited you to the org and the docs team! Thanks for your help in advance. 🏆

**Pull request merged**
