### PR TITLE
#406 added links to README.md

### PR DESCRIPTION
**Pull request by kitkatayama**
Add all locals links to README.md

### CODE REVIEW

**Comment by mischnic** [comment]
Why is this needed? There is a language chooser at the top:

Bildschirmfoto 2019-03-13 um 17 44 21

**Comment by DeMoorJasper** [comment]
@mischnic on local dev that doesn't work

**Comment by mischnic** [comment]
> on local dev that doesn't work

🙈 How could I miss that this changes the readme and not the actual page

**Comment by kitkatayama** [comment]
thank follow-up @DeMoorJasper :) 🙈

**Pull request merged**
