### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by gnapse**
Spanish translation for the website.

### CODE REVIEW

**Comment by kidandcat** [comment]
@devongovett Could you accept this PR soon?

We want to spread ParcelJS to the spanish community. I can't understand why it has to go so long when there are PR's (and dedicated people) like this one fully translated and ready to be deployed.

**Comment by gnapse** [comment]
Thanks @brandon93s! And thanks again to everyone who contributed, including @kidandcat and the folks on #57 that also started on a similar effort. Fixed on top of this work are welcome.

BTW @brandon93s, the website https://es.parceljs.org/ is not loading correctly. It appears to have some sort of issue with the certificate, probably not being associated still with the domain or something like that.

**Comment by devongovett** [comment]
Awesome, thanks for your work on this! Sorry for my slow responses, I've been super busy.

**Comment by kidandcat** [comment]
@devongovett Thanks for your time, and thanks @gnapse for the translation! let's make a great community around ParcelJS!

**Pull request merged**
